package(default_visibility = ["//visibility:public"])

java_library(
  name = 'scribe',
  exports = ["@scribe//jar"],
)

java_library(
  name = 'commons-codec',
  exports = ["@commons-codec//jar"],
)
